### ISSUE TITLE
prometheus java client introduced a breaking change

### ISSUE THREAD

**Issue by fsimmend** [prometheus/jmx_exporter#1133]
when using the exporter 1.1.0 our application does not start and errors with 

```
java.lang.NoSuchMethodError: 'boolean io.prometheus.metrics.expositionformats.PrometheusProtobufWriter.isAvailable()'
```

This is due to the fact, that we are including the prometheus java client in 1.3.5 and the exporter now requires 1.3.6 since the 1.1.0 version because it shades only part of the prometheus java client.

My impression was, that the agent is shading all of its dependencies so it can run isolated to the application it instruments. 

The change on the prometheus side was introduced in https://github.com/prometheus/client_java/pull/1190

**Comment by dhoard** [comment]
@fsimmend Inspecting various versions of the agent jars it appears that the shading has changed over time.

Looking through the project history (tickets/PRs), I don't see any definitive statement regarding the shading/shading approach.

The team will need to discuss the issue.

**Comment by dhoard** [comment]
@fsimmend I changed the shading with PR https://github.com/prometheus/jmx_exporter/pull/1150 which should resolve the issue.
